"""
Cougar Protocol Message Types

Implements message classes for the Cougar protocol, following the same pattern
as Kadcast messages but adapted for Cougar's header-first dissemination model.

Message Flow:
1. CougarHeaderMessage: Block header advertisement (push)
2. CougarBodyRequestMessage: Body pull request  
3. CougarBodyResponseMessage: Block body transfer
4. CougarTimeoutEvent: Handled in simulator (not network message)
"""

from typing import Dict,List, Any, Optional
import struct
import json


class CougarMessage:
    """
    Base class for all Cougar protocol messages.
    Following Kadcast pattern for consistency.
    """
    
    def __init__(self, message_type: str, sender_id: str):
        self.message_type = message_type
        self.sender_id = sender_id
        self.timestamp = 0
        self.size = 0  # Will be calculated in subclasses
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert message to dictionary for logging/debugging."""
        return {
            "message_type": self.message_type,
            "sender_id": self.sender_id,
            "timestamp": self.timestamp,
            "size": self.size
        }
    
    def _calculate_size(self) -> int:
        """Calculate message size in bytes. Override in subclasses."""
        raise NotImplementedError


class CougarHeaderMessage(CougarMessage):
    """
    Header advertisement message (push to all neighbors).
    
    Contains block header data generated by RealisticBlockGenerator.
    Size: Actual serialized header size (not fixed!)
    """
    
    def __init__(self, sender_id: str, block_hash: str, header_data: Dict[str, Any]):
        super().__init__("HEADER_ADVERTISEMENT", sender_id)
        self.block_hash = block_hash
        self.header_data = header_data
        
        # Use actual RealisticBlockGenerator serialization
        self.header_bytes = json.dumps(header_data).encode('utf-8')
        self.size = self._calculate_size()
    
    def _calculate_size(self) -> int:
        """Use actual serialized header size from RealisticBlockGenerator."""
        return len(self.header_bytes)
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "block_hash": self.block_hash,
            "header_size": len(self.header_bytes)
        })
        return base


class CougarBodyRequestMessage(CougarMessage):
    """
    Body pull request message.
    
    Sent from downstream peer to upstream peer to request block body.
    Size: 32 bytes (block hash)
    """
    
    def __init__(self, sender_id: str, target_peer_id: str, block_hash: str):
        super().__init__("BODY_REQUEST", sender_id)
        self.target_peer_id = target_peer_id
        self.block_hash = block_hash
        self.size = self._calculate_size()
    
    def _calculate_size(self) -> int:
        """Request message contains only block hash."""
        return 32  # SHA-256 hash
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "target_peer_id": self.target_peer_id,
            "block_hash": self.block_hash
        })
        return base


class CougarBodyResponseMessage(CougarMessage):
    """
    Body response message containing full block body.
    
    Contains transaction data generated by RealisticBlockGenerator.
    Size: Variable (depends on transaction count and sizes from realistic_payload)
    """
    
    def __init__(self, sender_id: str, target_peer_id: str, block_hash: str, 
                 transactions: List[Dict[str, Any]]):
        super().__init__("BODY_RESPONSE", sender_id)
        self.target_peer_id = target_peer_id
        self.block_hash = block_hash
        self.transactions = transactions
        
        # Use actual RealisticBlockGenerator transaction serialization
        self.body_data = json.dumps(transactions).encode('utf-8')
        self.size = self._calculate_size()
    
    def _calculate_size(self) -> int:
        """Body size is the actual serialized transaction data from realistic_payload."""
        return len(self.body_data)
    
    def to_dict(self) -> Dict[str, Any]:
        base = super().to_dict()
        base.update({
            "target_peer_id": self.target_peer_id,
            "block_hash": self.block_hash,
            "body_size": len(self.body_data),
            "transaction_count": len(self.transactions)
        })
        return base



# Message type constants for simulator
class CougarMessageType:
    """Constants for Cougar message types."""
    HEADER_ADVERTISEMENT = "HEADER_ADVERTISEMENT"
    BODY_REQUEST = "BODY_REQUEST"
    BODY_RESPONSE = "BODY_RESPONSE"

class CougarTCPModel:
    """Enhanced TCP transfer time calculation with real RTT data."""
    
    def __init__(self, geo_provider=None):
        self.initial_window_size = 536 * 4  # 4 MSS segments (2144 bytes)
        self.mss = 536  # Maximum Segment Size
        self.geo_provider = geo_provider  # ✅ GeoDataProvider reference
    
    def calculate_transfer_rtts(self, data_size_bytes: int) -> float:
        """
        Calculate number of RTTs needed for data transfer.
        
        Based on TCP congestion window growth:
        - If data fits in initial window: 0.5 RTT
        - Otherwise: 0.5 + additional RTTs for extra batches
        
        Args:
            data_size_bytes: Size of data to transfer
            
        Returns:
            Number of RTTs required
        """
        if data_size_bytes <= self.initial_window_size:
            print(f"DEBUG: Single batch, returning 0.5")
            return 0.5  # Single batch transfer
        
        # Calculate additional batches needed
        remaining_bytes = data_size_bytes - self.initial_window_size
        current_window = self.initial_window_size
        additional_rtts = 0
        
        while remaining_bytes > 0:
            additional_rtts += 1
            # TCP additive increase: window grows by MSS each RTT
            current_window += self.mss
            remaining_bytes -= current_window

            print(f"DEBUG: Final RTTs needed = {additional_rtts}")
        
        return 0.5 + additional_rtts
    
    def get_real_rtt(self, city1: str, city2: str) -> float:
        """Get real RTT between cities using GeoDataProvider."""
        if self.geo_provider:
            return self.geo_provider.get_rtt(city1, city2)  # ✅ Gerçek RTT verisi
        else:
            return 100.0  # Fallback
    
    def get_header_transfer_time(self, rtt_ms: float) -> float:
        """Calculate header transfer time (always fast)."""
        return 0.5 * rtt_ms
    
    def get_body_request_time(self, rtt_ms: float) -> float:
        """Calculate body request time."""
        return 0.5 * rtt_ms
    
    def get_body_transfer_time(self, body_size: int, rtt_ms: float) -> float:
        """Calculate body transfer time based on size."""
        rtts_needed = self.calculate_transfer_rtts(body_size)
        return rtts_needed * rtt_ms
    
    def get_timeout_duration(self, body_size: int, rtt_ms: float) -> float:
        """
        Calculate timeout for body requests.
        Paper specifies: 2 × RTTs required for transfer
        """
        body_transfer_time = self.get_body_transfer_time(body_size, rtt_ms)
        return 2.0 * body_transfer_time
    
    def get_timeout_duration_with_cities(self, body_size: int, sender_city: str, receiver_city: str) -> float:
        """Calculate timeout using real RTT data between cities."""
        real_rtt_ms = self.get_real_rtt(sender_city, receiver_city)  # ✅ Gerçek RTT
        body_transfer_time = self.get_body_transfer_time(body_size, real_rtt_ms)
        return 2.0 * body_transfer_time
    
    def get_enhanced_timeout_stats(self, body_size: int, sender_city: str, receiver_city: str) -> Dict[str, Any]:
        """Get detailed timeout calculation breakdown with real RTT data."""
        real_rtt_ms = self.get_real_rtt(sender_city, receiver_city) #-> İKİ ŞEHİR ARASI RTT DEĞERİ IN MS 
        rtts_needed = self.calculate_transfer_rtts(body_size) # -> KAŞ KEZ O RTT KULLANILACAK
        body_transfer_time= real_rtt_ms * rtts_needed
        timeout = 2.0 * body_transfer_time

            # ✅ FULL DEBUG:
        print(f"TIMEOUT DEBUG:")
        print(f"  body_size: {body_size}")
        print(f"  real_rtt_ms: {real_rtt_ms}")
        print(f"  rtts_needed: {rtts_needed}")
        print(f"  body_transfer_time: {body_transfer_time}")
        print(f"  timeout: {timeout}")
        
        return {
            "sender_city": sender_city,
            "receiver_city": receiver_city,
            "real_rtt_ms": real_rtt_ms,
            "body_size_bytes": body_size,
            "rtts_needed": rtts_needed,
            "body_transfer_time_ms": body_transfer_time,
            "timeout_ms": timeout,
            "timeout_seconds": timeout / 1000.0
        }    